version: '3'

services:
  validator_service:
    container_name: fhir-validator-service
    image: infernocommunity/fhir-validator-service
    environment:
      DISABLE_TX: 'false'
    volumes:
      - ./igs:/home/igs
    ports:
      - "4567:4567"

  matchbox:
    container_name: matchbox
    image: eu.gcr.io/fhir-ch/matchbox:v141
    environment:
      - hapi.fhir.implementationguides.1.url=https://worldhealthorganization.github.io/ddcc/package.tgz
      - hapi.fhir.implementationguides.1.name=fhir.who.ddcc-vs
      - hapi.fhir.implementationguides.1.version=0.2.1
    ports:
      - "8080:8080"