name: Lint and Test

on: [push, pull_request]

jobs:
  verify:
    name: Run Lint and Tests
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1

    - run: docker-compose up -d matchbox

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - run: npm install

    - run: npm run lint

    - name: Wait for validator to load IGs
      run: sleep 30s

    - run: npm run test
      env:
        VALIDATOR_SERVICE_URL: http://localhost:8080/matchbox/fhir/$validate
        CI: true

    - name: Dump docker logs on failure
      if: failure()
      run: docker logs matchbox
